# Site settings
title: 0x5t's Blog
SEOTitle: 0x5t Blog
header-img: img/home-bg.jpg
email: 
description: "0x5t's Blog | Ethical Hacking, CTFs, & More"
keyword: "0x5t, Ethical Hacking, CTF, Web Exploitation, GitHub Pages, Penetration Testing"
url: "0x5t.github.io" # your host, for absolute URL
baseurl: "" # e.g., '/blog' if hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: 0x5t
twitter_username: 0x55t
#facebook_username:  your_facebook_username_here
#linkedin_username:  your_linkedin_username_here

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
  ]
anchorjs: true

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Netease settings
netease_comment: false

# Analytics settings
ga_track_id: "G-L60Z89VR35" # Google Analytics Tracking ID
ga_domain: 0x5t.github.io

# Sidebar settings
sidebar: true
sidebar-about-description: "0x5t – Ethical Hacker & CTF Enthusiast"
sidebar-avatar: https://github.com/0x5t.png # absolute URL for your avatar

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Connect on GitHub", href: "https://github.com/0x5t" },
  ]
